### ISSUE TITLE
CRT frame image in png format?

### ISSUE THREAD

**Issue by hizzlekizzle** [mattiasgustavsson/newpixie#1]
Hi there, I work on shaders for libretro and had previously ported your CRT shadertoy. One of our users apparently contacted you a few days ago and then notified me that you had a more advanced version of the shader and linked me to this repo.

I think I have most of it ported and working, but I wondered if you had the frame image handy as a png?

**Comment by mattiasgustavsson** [comment]
That's awesome :D I am always happy when people find my code useful :) And this version is a lot more efficient than the shadertoy one, mostly because of the separate blur pass. It also looks better, as it has a "ghost trail" effect.

I've uploaded the crtframe as a png here: https://github.com/mattiasgustavsson/libs/blob/master/crtframe.png

Anything else, just let me know.

**Comment by hizzlekizzle** [comment]
This looks perfect, thanks!
